import Head from 'next/head'

import '../../styles/globals.css'
import styles from '../../styles/Home.module.css'

import NavBar from '../components/navbar'

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar></NavBar>
      
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
